apiVersion: v1
kind: Secret
metadata:
  name: quay-basic-secret
  annotations:
    tekton.dev/docker-0: https://quay.io
type: kubernetes.io/basic-auth
stringData:
  username: azkaoru
  password: towa0817
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
#secrets:
#- name: quay-basic-secret
