apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: resource-example-task
spec:
  inputs:
    params:
      - name: pathToPomFile
        default: "/workspace/git-workspace/pom.xml"
      - name: tlsverify
        default: "false"
      - name: quayId
        default: "Quayuser"
      - name: quayPass
        default: "Quaypass"
      - name: ocArgs
        default: "help"
    resources:
      - name: git-workspace
        type: git
  outputs:
    resources:
      - name: app-image
        type: image
      - name: openshift-image
        type: image
  steps:
    - name: build-war
      image: quay.io/azkaoru/maven354-java8-devel
      command:
      - mvn
      args:
        - -f
        - $(inputs.params.pathToPomFile)
        - clean
        - package
    - name: build-image
      image: quay.io/buildah/stable
      workingdir: /workspace/git-workspace
      command: ['buildah', 'bud', '--tls-verify=$(inputs.params.tlsverify)', '--layers', '-f', '/workspace/git-workspace/Dockerfile', '-t', '$(outputs.resources.app-image.url)', '.']
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
    - name: push-image-to-quay
      image: quay.io/buildah/stable
      command: ['buildah', 'push', '--creds' , '$(inputs.params.quayId):$(inputs.params.quayPass)', '--tls-verify=$(inputs.params.tlsverify)', '$(outputs.resources.app-image.url)', 'docker://$(outputs.resources.app-image.url)']
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
    - name: tag-image-for-openshift
      image: quay.io/buildah/stable
      command: ['buildah', 'tag', '$(outputs.resources.app-image.url)', '$(outputs.resources.openshift-image.url)']
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
    - name: push-image-to-openshift
      image: quay.io/buildah/stable
      command: ['buildah', 'push', '--tls-verify=$(inputs.params.tlsverify)', '$(outputs.resources.openshift-image.url)', 'docker://$(outputs.resources.openshift-image.url)']
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
    - name: oc-apply
      image: quay.io/openshift-pipeline/openshift-cli:0.7.0
      command: ["/usr/local/bin/oc"]
      args:
        - "$(inputs.params.ocArgs)"
  volumes:
    - name: varlibcontainers
      emptyDir: {}
