apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
 name: picalc-pipeline-run
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: picalc-git
  params:
    - name: pathToYamlFile
      value: "knative/picalc.yaml"
    - name: imageUrl
      value: "image-registry.openshift-image-registry.svc:5000/fooproject/picalc"
    - name: imageTag
      value: "1.0"
  serviceAccount: pipeline
